# Generated by Django 3.1.5 on 2021-01-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='', verbose_name='default.png'),
        ),
    ]
